# Site settings

# Base hostname & protocol for your site
url: "micutio.github.io"
# Subpath of your site, e.g. /blog/
baseurl: ""
# Title of the website 
title: "Artificial Life Simulations - From Simple to Complex"
description: "A website/blog about building simulations and exploring complexity"
keywords: "artificial life, complexity, cellular automaton, agents, agent-based, simulation"

email: "wagner.mchl@googlemail.com"
github_username:  "micutio"

google_analytics: "UA-79753372-1"
repo: https://github.com/Micutio/micutio.github.io
disqus_shortname: "micutiogithubio"
disqus_site_shortname: "micutiogithubio"

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 100
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


